[package]
name = "ydj-mixer-engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "ydj_mixer_engine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
rand = "0.9"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
